# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
author: Nutchanon J
title: Nutchanon J's Stories
email: "nutchanon.non@outlook.co.th"
description: >- # this means to ignore newlines until "baseurl:"
  รวมบทความของนิสิตคณะวิศวะฯ คนหนึ่งในจุฬา ที่เรียนภาคไฟฟ้า
baseurl: "/myblog" # the subpath of your site, e.g. /blog
url: "https://nutchanonj.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll

tagline: Nutchanon Jariyanurut Personal Blog

repository: "nutchanonj/"

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap

# A list of the pages to display in the navigation bar
header_pages:
  - toc.md
  - about.md
  - contact.md

aux_links:
  "เว็บหลัก":
    - "https://nutchanonj.github.io/"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - update_boostrap.sh

show_excerpts: true

paginate: 9

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
